spring.application.name=tekravio-notification-service
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


#jwt-token
jwt.token.secret=IFAdkWczFIqcRZNIAylg9hy0qSP4TqFaPPUJlgM5J40=
jwt.token.expire=3600000

#Roles access details
update.product.roles=SUPER_ADMIN,ADMIN
order.update.status.roles=SUPER_ADMIN,ADMIN



# Actuator (Health Checks)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
security.basic.enabled=false
management.security.enabled=false


#redis-cache
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.ttl.config=categories:36000,user:36000

#tekravio
tekravio.notification.retry.max-attempts=3
tekravio.notification.retry.initial-interval=1000
tekravio.notification.retry.multiplier=2.0
tekravio.notification.retry.max-interval=30000
tekravio.notification.kafka.topics.email=notifications.email
tekravio.notification.kafka.topics.sms=notifications.sms
tekravio.notification.kafka.topics.whatsapp=notifications.whatsapp
tekravio.notification.kafka.topics.push=notifications.push
tekravio.notification.kafka.topics.dlq-suffix=.dlq
tekravio.notification.kafka.consumers.email-concurrency=3
tekravio.notification.kafka.consumers.push-concurrency=5

#
notification.auth.client-id=tekravio-client
notification.auth.client-secret=secret123

#Roles access details
notification.system.roles=SUPER_ADMIN,ADMIN

encryption.secret=0123456789abcdef0123456789abcdef

#Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
